### ISSUE TITLE
Drupal: fix multisite installation on a different domain

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#1]
Drupal requires a specific folder name inside the `sites` folder.
Before running the actual installation, we have rename such folder to reflect the current domain

**Comment by nikosdion** [comment]
OK, please do that.

**Comment by nikosdion** [comment]
I assume these commits close this issue? If so, please close it.

**Comment by nikosdion** [comment]
And remember to add CHANGELOG entries to Akeeba Solo about this fix ;)

**Comment by tampe125** [comment]
Yep, it was closed with those commits.
