### ISSUE TITLE
Update output directory on site restoration

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#16]
if the user set a custom output directory, ANGIE will not replace it, causing an issue while taking a new backup.
We should update it during restoration or at least warn the user to manually do that once the restoration is completed.

**Comment by nikosdion** [comment]
No. This is up to the user. If you would implement this suggestion it would break restoring on the same site. Moreover it would require ANGIE to know how data is stored by the Engine in the DB which is asking for trouble. 

Just close this issue. In ten years apparently only one person was confused.

**Comment by tampe125** [comment]
ROFL! Ok, we can live with that ;)
