### ISSUE TITLE
Wordpress: warn about hardcoded HOME/SITE variables

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#18]
Wordpress allows users to hardcode the HOME/SITE variables inside the `wp-config.php` file.
This means that even if we perform a full restoration and replace within the database, the restored site will always point to the old site (yeah...)
At this point we have two options: warn the user or silently remove such lines when we write the new configuration file.

**Comment by nikosdion** [comment]
We should go with option 3: if these variables exist in WP-config.php replace them. If they don't exist do nothing. Should happen at the finalization step when we are touching that file. 

TBH I thought we were doing that already. Apparently I was wrong :(
