### ISSUE TITLE
Wordpress: double check wp-config encoding

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#2]
Today we had a support request from a user receiving a white screen of death when trying to login to his restored site.
After several time spent in debugging, I discovered that the `wp-config.php` file had the `UTF-8 with BOM` encoding. Such BOM was outputted, causing the `Headers already sent error`, once I removed it, everything went fine.

In your experience, should we double check if the encoding is correct before writing the `wp-config.php` file? Can PHP do this in a reliable way?

**Comment by nikosdion** [comment]
Good catch. We should check if there is a BOM and remove it. BOMs are inserted when a user edits wp-config.php with a plain text editor on Windows and has forgotten about the insert BOM feature of the editor being turned on by default.

And yes, PHP can do it. See https://anupamsaha.wordpress.com/2011/08/02/detecting-utf-byte-order-mark-using-php/
