### ISSUE TITLE
Wordpress: Better UX in the Replacement step

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#24]
We already have the code running in the same way as the backup, using our timer and hardcoded limits, instead of having data replacement as part of the finalization we should have it as its own step.

We can easily add min/max exec time and runtime bias parameters on that page as "Advanced settings". The page where the replacement runs should display a Back button (in the main content area) if we don't get a response from the server within 20 seconds _or_ if we get an error response.
Finally we should do the same as Akeeba Backup: wait 10 seconds, retry, repeat up to three times.

Addendum 1: Add a placeholder URL so we can write an article about it and link to it if the replacement fails.
Addendum 2: Improve logging in the replacement step

**Comment by nikosdion** [comment]
I am bumping this to priority 1 since the improvements will solve lots of the reported restoration issues. I am now looking at a site with a bazillion big tables that naturally take forever to process. Any small disturbance in the network throws off the restoration.
