### ISSUE TITLE
Database: Display warning if large tables are detected

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#31]
ANGIE should check if `installation/large_tables_detected` exists and print a warning message in the Database Setup page that the maximum column length detected is X Mb (detected value + 512Kb, rounded to two digits). So if the user gets a database error they must make sure that the max_packet_size is set to at least that.

**Comment by nikosdion** [comment]
We have detected that the required maximum size for a single row SQL query is %s Mb for your site. This is larger than the average site. If you receive a database error code 1153; or error message "ER_NET_PACKET_TOO_LARGE)"; or error message "Got a packet bigger than 'max_allowed_packet' bytes" then please ask your host to set the value of the `max_allowed_packet` configuration variable of your database server to at least %s Mb.

The two values are:
1. The size of the maximum SQL query generated during backup in Mb, rounded in 2 decimals
2. floor(size_as_described_above) + 1. For example floor(2.24) + 1 = 2 + 1 = 3
