### ISSUE TITLE
WordPress: Support WP Super Cache

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#49]
It seems that WP Super Cache supports constants to be defined in the wp-config.php.  
For example `WPCACHEHOME` points to the plugin path.  
When we restore the website, we have to update such value, too, otherwise the restored site will be broken.

Given that the plugin WP Super Cache is pretty common, I think we should support that, even their implementation is not ideal

**Comment by nikosdion** [comment]
We can post-process wp-config.php in the same we post-process the .htaccess. Please add that to the data processing step.
