### ISSUE TITLE
Allow to rename installation folder

### ISSUE THREAD

**Issue by piotrmocko** [akeeba/angie#55]
Allow to rename the installation folder

https://github.com/akeeba/angie/blob/ae53982c4ccf3dfecdcf4e50d1d559b360ec1b5e/angie/platforms/joomla/models/joomlasetup.php#L471

Change to

    require_once APATH_INSTALLATION . '/framework/utils/password.php';

https://github.com/akeeba/angie/blob/ae53982c4ccf3dfecdcf4e50d1d559b360ec1b5e/angie/platforms/wordpress/models/wordpresssetup.php#L20-L21

Change to

    $install_dir = basename(APATH_INSTALLATION);
    $siteurl = str_replace('/' . $install_dir . '/', '', AUri::root());
    $homeurl = str_replace('/' . $install_dir . '/', '', AUri::root());

**Comment by nikosdion** [comment]
The name of the installation folder is hard-coded for very good reasons. There is the need to know _where_ the installer will be extracted on the file system for the following features to work:

* Password protect ANGIE. A virtual file is added at backup time.
* Database backup. A file with the databases manifest is added at backup time and read during restoration. Moreover, all the SQL files are added to the archive using the installation folder naming convention at backup time.
* Several files are added at backup time into the installation folder to tell the restoration engine about the previous state of the site and used to show you information about the old site, determine if the site was moved, determine if the new PHP version is different than the one you backed up from etc. In fact, without these files restoring a WordPress site would be a horribly frustrating experience.
* Putting the installer in the archive. We do a JPA-to-JPA copy with the fixed paths stored in the installer image files. Transforming the pathnames is not really something we needed and it's not been implemented.
* Off-site folder inclusion. A file with the off-site folders manifest is added to the archive at backup time.
* Akeeba Backup's integrated restoration. We do post-restoration, CMS-specific finalization and remove the installation folder after we're done.
* Kickstart's Clean Up for the same reason as above.
* Kickstart's "Run the Installer" feature.
* Akeeba UNiTE (the whole application).

What you are proposing, if we were to _really_ give you the option to rename the installation folder, is roughly four weeks worth of work and adding several configuration options in several software. Moreover, it's a massive b/c break, making it a support headache.

Even worse, there is no good reason to do it. Any security concerns can be mitigated with 1. ANGIE password and 2. simple server-level password protection of the installation folder. The former can always be added at backup time. Either can be added right before or right after archive extraction.

**Comment by piotrmocko** [comment]
Thanks for the explanation. I don't need an option to rename this folder. The only think I wanted is that after a manual extraction of a backup with Kickstart I can rename the installation folder to something else, that Joomla! won't redirect any user to that folder, but that user will see that website is offline as I have put the website in a maintenance model.

I would appreciate if you could apply those changes. It should be a quick fix to allow to use AGINE manually with a different folder name.

**Comment by piotrmocko** [comment]
Thanks for that instruction. But it would be grate if you could apply those changes, it doesn't do anything if you want to use the installation directory, but would help me a lot.

**Comment by piotrmocko** [comment]
Thanks for that instruction. But it would be grate if you could apply those changes, it doesn't do anything if you want to use the installation directory, but would help me a lot. It is the only place where you are not using APATH_INSTALLATION
