### ISSUE TITLE
Console errors about missing fonts

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#59]
ANGIE tries to load missing FEF fonts: OpenSans-Bold.ttf Montserrat-Regular.ttf OpenSans-Italic.ttf
Should we include in the installer or remove them from the CSS?
Is there an option to link fef.min.css to avoid using those fonts?

Paging @nikosdion

**Comment by nikosdion** [comment]
Good catch. We will address it today. Very good timing too, your ticket came just before I tagged a new FEF release...
