### ISSUE TITLE
Prestashop: Restore with a different prefix

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#6]
It seems that during the restoration we are not reading the correct prefix submitted with ANGIE.
Ticket reference [#25032](https://www.akeebabackup.com/support/akeeba-solo/25032-sql-select-min-id-shop-from-shop-when-trying-to-restore-servers.html)

**Comment by nikosdion** [comment]
Can you fix it before I get back?

**Comment by tampe125** [comment]
It seems that the problem is inside the SQL file: tables are stored with `#__ps_foobar`. I asked more details to the customer in order to replicate it.

**Comment by nikosdion** [comment]
He has left the prefix empty?

**Comment by tampe125** [comment]
No, she claims the prefix is `ps_`. I just tried and everything is working fine, I can't reproduce it.

**Comment by tampe125** [comment]
Closed since I can't replicate the error reported by the user.
