### ISSUE TITLE
(HTTP ERROR 500) Finalise view with Google Chrome

### ISSUE THREAD

**Issue by twister65** [akeeba/angie#66]
When we click the next button in the setup view, with Google Chrome, there is an Http Error 500.
The finalise view is corectly displayed with other browsers (Firefox, Opera, ...).
HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by twister65** [comment]
It works if you open it in a new tab.

**Comment by nikosdion** [comment]
I cannot reproduce this issue following your instructions. It would appear that this is not a bug, it's a support request. We (Akeeba Ltd) will only provide support to our subscribers through our site's Support section.

Of course if you do find a way to reproduce this issue consistently *on a different site and server* please let me know how and I will take a look.
