### ISSUE TITLE
Raise the allowed packet before restoring the database

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#7]
Before performing the restoration, we can try to raise the limit of the `max_allowed_packet` option for the current session only:

    set session max_allowed_packet=1024*1024*50;

We have to do it for every driver we currently have inside ANGIE.
That should allow restoring columns with large quantities of data inside the database.

**Comment by tampe125** [comment]
Sadly, MySQL is broken. `max_allowed_packet` can be changed **only at startup**. 
If I try to change the GLOBAL value, it doesn't change; moreover the session variable is read-only :(

Some resources:
http://blog.webyog.com/2009/08/10/mysql-server-has-gone-away-part-1-max_allowed_packet/
https://bugs.mysql.com/bug.php?id=52802
https://bugs.mysql.com/bug.php?id=52805

**Comment by nikosdion** [comment]
Reading the bug reports it seems that on some versions of MySQL you can set the session variable, on some others you can set the global variable (and on some you are out of luck).

I suggest that we try to run TWO queries which we can expect to fail:
```sql
SET GLOBAL max_allowed_packet=67108864;
SET SESSION max_allowed_packet=67108864;
```
Try running both, *each one in a separate try/catch block*. In the best case scenario we have a healthy packet size and all is good. In the worst case scenario restoring very large rows will fail just like before.
