### ISSUE TITLE
Improve failed log queries 

### ISSUE THREAD

**Issue by tampe125** [akeeba/angie#74]
When a query fails (and we told ANGIE to ignore the error) everything is saved into a file named `failed_queries_site_sql.log`.  
The problem is, such file is not very handy to use. If you have large queries (like trying to restore AcyMailing newsletter tables), it **VERY** hard to do.  
On each line, there will be two info for each query that failed: the error with the "concrete" query, and the abstract one, without the table prefix.
Statements are not separated by semi-colons.  

This means that after the user identified the issue and know what he should change, even it's a simple Search&Replace fix, it has to spend a lot of time to cleanup the log and make usable.  
Case in point: I just helped a customer to restore its database, where I only had to remove the table option `PAGECHECKSUM=1`. It was a simply `sed` statement, but I spent more than an hour to fix everything else.  

My suggestion is to create _another_ file meant to be easily replayed: queries should be there, with the suffix already change, each one of them separated by a semi-colon.  
So it will be way easier to fix the import and then upload to phpMyAdmin or similar.

**Comment by nikosdion** [comment]
Change the logging to only include the concrete query and add a semicolon. No reason to make things overly complicated.
